gmsh.initialize();

% Set a full onelab db.
gmsh.onelab.set(sprintf([ ...
    '{ "onelab":{ ' ...
    '  "creator":"My app", ' ...
    '  "version":"1.3", ' ...
    '  "parameters":[ ' ...
    '    { "type":"number", "name":"number 1", "values":[ 1 ]  }, ' ...
    '    { "type":"string", "name":"string 1", "values":[ "hello" ]  } ' ...
    '  ] } }']));

% Set a list of parameters.
gmsh.onelab.set(sprintf([ ...
    '[ ' ...
    '  { "type":"number", "name":"number 2", "values":[ 3.141592 ], ' ...
    '    "attributes":{ "Highlight":"Red" }  }, ' ...
    '  { "type":"string", "name":"string 2", "values":[ "hello again" ]  } ' ...
    ']']));

% Set a single parameter.
gmsh.onelab.set(sprintf([ ...
    '{ "type":"number", "name":"check 1", "values":[ 0 ], "choices":[0, 1]  }']));

% Get the full parameter as JSON, edit an attribute, set it back. MATLAB's
% jsondecode/jsonencode round-trip is the equivalent of Python's json module.
p = jsondecode(gmsh.onelab.get("check 1"));
p.attributes.Highlight = "Blue";
gmsh.onelab.set(jsonencode(p));

% Shorter way to just change the value.
gmsh.onelab.setNumber("check 1", [1]);
gmsh.onelab.setString("string 1", {'goodbye'});

% Remove a parameter.
gmsh.onelab.clear("string 2");

gmsh.finalize();
