function prepro(filename)
%PREPRO  Port of prepro.py: simple FE-style preprocessor + ONELAB parameters.
%   prepro(FILENAME) optionally opens FILENAME before setting up parameters.
%   The Python version drives the FLTK GUI; we port the parameter-set + dry
%   "runSolver" branch (the non-interactive arm).
    gmsh.initialize();
    if nargin >= 1 && ~isempty(filename)
        try
            gmsh.open(filename);
        catch
        end
    end

    parameters = sprintf(['[ ' ...
        '{ "type":"number", "name":"ONELAB Context/Curve Template/0Boundary condition", "values":[0], "choices":[0, 1], "valueLabels":{"Temperature":0,"Flux":1} }, ' ...
        '{ "type":"number", "name":"ONELAB Context/Curve Template/1Value", "values":[20], "min":0, "max":100, "step":0.1 }, ' ...
        '{ "type":"string", "name":"ONELAB Context/Curve Template/2Action", "values":["Some action"], "attributes":{"Macro":"Action","Aspect":"MiddleButton"} }, ' ...
        '{ "type":"string", "name":"ONELAB Context/Curve Template/3Other action", "values":["Some other action"], "attributes":{"Macro":"Action","Aspect":"RightReturnButton"} }, ' ...
        '{ "type":"number", "name":"ONELAB Context/Surface Template/0Material", "values":[1], "choices":[0,1,2], "valueLabels":{"User-defined":0,"Steel":1,"Concrete":2}, "attributes":{"ServerActionHideMatch":"ONELAB Context/Surface Template/1.*","ServerActionShowMatch 0":"ONELAB Context/Surface Template/1.*","ServerActionSet 1":"%%10Cond, 205, %%11Diff, 97","ServerActionSet 2":"%%10Cond, 37, %%11Diff, 12"} }, ' ...
        '{ "type":"number", "name":"ONELAB Context/Surface Template/10Cond", "label":"Conductivity", "values":[205], "min":0.1, "max":500, "step":0.1, "visible":false }, ' ...
        '{ "type":"number", "name":"ONELAB Context/Surface Template/11Diff", "label":"Diffusivity", "values":[97], "min":10, "max":1200, "step":0.1, "visible":false }, ' ...
        '{ "type":"string", "name":"ONELAB/Button", "values":["Run","run"], "visible":false }, ' ...
        '{ "type":"number", "name":"0Modules/Solver/My solver/1Some flag", "values":[0], "choices":[0, 1] }, ' ...
        '{ "type":"number", "name":"0Modules/Solver/My solver/2Some parameter", "values":[1.234], "min":0, "max":10, "step":0.1 }, ' ...
        '{ "type":"number", "name":"0Modules/Solver/My solver/3Some choice", "values":[0], "choices":[0,1], "valueLabels":{"Choice 1":0,"Choice 2":1} }, ' ...
        '{ "type":"string", "name":"0Modules/Solver/My solver/3Some input", "values":[""] }, ' ...
        '{ "type":"string", "name":"0Modules/Solver/My solver/5Some action", "values":["select entity"], "attributes":{"Macro":"Action"} }, ' ...
        '{ "type":"string", "name":"0Modules/Solver/My solver/6Some other action", "values":["do something else"], "attributes":{"Macro":"Action","Aspect":"Button"} } ' ...
        ']']);

    gmsh.onelab.set(parameters);

    runSolver();
    gmsh.finalize();
end


function runSolver()
    fprintf('parameters = %s\n', gmsh.onelab.get());
    fprintf('running the solver with the given parameters...\n');
    diffus = gmsh.onelab.getNames("ONELAB Context/.*([0-9]+)/11Diff");
    for k = 1:numel(diffus)
        fprintf('%s = %g\n', diffus{k}, gmsh.onelab.getNumber(diffus{k}));
    end
end
